apiVersion: v1
kind: Secret
metadata:
  name: bizaway-api-secret
  namespace: bizaway
type: Opaque
stringData:
  # MongoDB connection string for the application
  MONGODB_URI: "mongodb://root:supersecurepassword@mongo:27017/tech_challenge?authSource=admin"
